### ISSUE TITLE
Issue while installing GliaWidgets using  CocoaPods 

### ISSUE THREAD

**Issue by shrawan2015** [salemove/ios-sdk-widgets#210]
**While installing GliaWidgets using  CocoaPods we are having issue:-**

Platform:- 
Xcode  : 13.2.1
Pod version : 1.11.2

Podfile:-
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/salemove/glia-ios-podspecs.git'
pod 'GliaWidgets', git: 'https://github.com/salemove/ios-sdk-widgets', tag: '0.6.0'

Error:-
<img width="1376" alt="Screenshot 2022-01-13 at 6 48 51 PM" src="https://user-images.githubusercontent.com/10405305/149337433-f891da06-fa5a-461a-bf0a-8ca82f89eeff.png">

**Comment by dukhovnyi** [comment]
@shrawan2015 based on the log message you have some trouble with checking out `webrtc` repository. Try to clean up your Cocoapods cache, verify that you installed [Git LFS](https://git-lfs.github.com/), and try again to install pods.

**Comment by dukhovnyi** [comment]
no response for a long time. closing the issue for now.
