### ISSUE TITLE
Update README for CocoaPod Install Instructions 

### ISSUE THREAD

**Issue by nlabarbera** [salemove/ios-sdk-widgets#354]
The README with the updated accurate CocoaPod installation instructions. Those instructions didn't work and I had to go to the issues section and read the thread to locate the correct and updated instructions. Thank you!

**Comment by nlabarbera** [comment]
Delete -
`# Podfile

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/salemove/glia-ios-podspecs.git'

user_frameworks!

target 'YOUR_TARGET_NAME' do
    pod 'GliaWidgets', git: 'https://github.com/salemove/ios-sdk-widgets', tag: 'SDK_VERSION'
end
`

Replace With - 
`source 'https://github.com/salemove/glia-ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'MyProject' do
  use_frameworks!

  pod 'GliaWidgets'

end`

**Comment by dukhovnyi** [comment]
@nlabarbera we will update it today.
Please use this sample to integrate with Cocoapods
```
# Podfile

source 'https://github.com/salemove/glia-ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

user_frameworks!

target 'YOUR_TARGET_NAME' do
    pod 'GliaWidgets'
end

```

**Comment by nlabarbera** [comment]
Sweet thank you all so much!! Is there a sandbox to develop in?

**Comment by dukhovnyi** [comment]
What kind of sandbox feature would you like to have?

**Comment by nlabarbera** [comment]
We are good - I was able to get one! Thank you a ton for all your help!
